### ISSUE TITLE
Is this lib fork-safe?

### ISSUE THREAD

**Issue by xsren** [eht16/python-logstash-async#10]
Hello! Can I use this log handler in multi processing program in UNIX/LINUX system?

Thanks for your great job!

**Comment by eht16** [comment]
Yes, I don't know of any problems.
I use python-logstash-async in a couple of web services powered by uwsgi with 4 processes and each with 12 threads and noticed no problems so far.
If your processes issue lots of messages you might notice a few delays due to locks to the sqlite database. This is nothing critical, just delays the message transport a bit and only happens on high traffic log message rates. Still, I plan to address this issue soon.

Feel free to re-open for further questions or reports.

**Comment by xsren** [comment]
Thanks for your reply. I will use use it in my project.
