### ISSUE TITLE
Add module to extras

### ISSUE THREAD

**Issue by szechyjs** [eht16/python-logstash-async#14]
How can I add the `module` attribute to the default extras?

https://docs.python.org/2/library/logging.html#logrecord-attributes

**Comment by eht16** [comment]
Currently, it's not possible because `module` as most of the other default attributes are blacklisted. The rationale was to not include those accidentally.
You can easily remove `module` from the list in https://github.com/eht16/python-logstash-async/blob/master/logstash_async/formatter.py#L23.

Maybe it's worth to make this list more easy configurable via logging configuration?
Or at least more easy configurable via Python code.

**Comment by szechyjs** [comment]
That would be great! I'm working on migrating an existing logging implementation that uses `%(module)s` in addition to the extras you already have defined.

https://github.com/eht16/python-logstash-async/blob/master/logstash_async/formatter.py#L156-L165

**Comment by eht16** [comment]
You can now modify the list of excluded LogRecord attributes.
For general information see http://python-logstash-async.readthedocs.io/en/latest/config.html#module-constants, in detail you probably want something like the following:
```python
from logstash_async.constants import constants
constants.FORMATTER_RECORD_FIELD_SKIP_LIST.remove('module')
from logstash_async.handler import AsynchronousLogstashHandler
```

HTH.
A new release including this change will follow soon (a few days at max).
