### ISSUE TITLE
Can't create several handlers with different databases

### ISSUE THREAD

**Issue by mzominy** [eht16/python-logstash-async#30]
Hi, thanks for the great work on the lib!

The below code opening two different databases won't work.

I don't need a fix, it's to let you and other users know of the issue.

```
import logging
import sys
from logstash_async.handler import AsynchronousLogstashHandler

test_logger1 = logging.getLogger('python-logstash-logger')
test_logger1.setLevel(logging.INFO)
test_logger1.addHandler(AsynchronousLogstashHandler(
    'nowhere.test.com',
    5002,
    database_path='handler_1.sqlite',
))

test_logger1.info('logger1')


test_logger2 = logging.getLogger('python-logstash-logger2')
test_logger2.setLevel(logging.INFO)
test_logger2.addHandler(AsynchronousLogstashHandler(
    'nowhere.test.com',
    5000,
    database_path='handler_2.sqlite',
))

test_logger2.info('logger2')  # goes into first database
```

**Comment by eht16** [comment]
See #32 for hopefully clarifying documentation about the fact.
Actually having a single database for all handlers is by design as there is a single worker thread which processes the log events from all handlers.

This could be improved by starting a worker thread per database path and maintain some dictionary about the active worker threads. However, I think for the most use cases a single shared database is sufficient.

Feedback for the documentation update is welcome.
