### ISSUE TITLE
Lost messages if process after process quit

### ISSUE THREAD

**Issue by suvari3V** [eht16/python-logstash-async#33]
Hello,

I am running an API where I am logging some data to Logstash.
It seems that there are lots of lost messages if process quit and messages are still not send to Logstash.
If I set 30 secs sleep at the end of the process to test if is alright but it does not work otherwise.

I assume that for LRP it is going to work perfectly fine but what is happening if process is created and exits soon?

I am using following:
- ELK 6.4.3
- Ubuntu 18.04
- Python 3.7.1

Could you suggest how to workaround it?

Thanks

**Comment by animalmutch** [comment]
Hi. Experiencing the same problem (I think). I'm running a simulation, and logging results to elasticsearch via logstash-async, but if the simulation runs too fast, it finishes before all the logs have been sent through. I assumed that a thread would keep going and logging what's in the database, but I guess that the logging handler must run as a daemon thread and therefore shut down when the main program exits. Is there any way to change this (except hacking the code)? Thanks

**Comment by suvari3V** [comment]
I believe it is pretty much the same issue @animalmutch.

**Comment by ypid-geberit** [comment]
Hey guys, I experienced the same behavior in testing. In my use case, I have a dedicated Python script which gets logstash-async sqlite DB files, and sends the events contained in them to Logstash. To do this reliable, I found and implemented the following solution: https://github.com/geberit/e2e-tests/blob/4f8a08139285ce709ef2e8cf5cec0603a61a1446/tools/get_and_process_events_files.py#L52-L61

In short:

```Python
logstash_handler._start_worker_thread()
logstash_handler.flush()
```

The debugging session is some time ago so I can not tell you the details now but this works reliable for me since I implemented it.
