### ISSUE TITLE
Django settings vs manually logging- what am I missing?

### ISSUE THREAD

**Issue by jordotech** [eht16/python-logstash-async#43]
Hopefully it's something obvious that I'm missing but I am unable to get this working with Django logging settings but programmatically sending a message does work.  Maybe you can see something before I do a deep dive into the internals.

I have logging enabled so I can see when messages are received to my remote logstash server.

settings.py:
```
LOGGING = {
    'version': 1,
    'formatters': {
        'logstash': {
                  '()': 'logstash_async.formatter.LogstashFormatter',
                  'message_type': 'django',
              },
    },
    'handlers': {
        'logstash': {
                  'level': 'DEBUG',
                  'class': 'logstash_async.handler.AsynchronousLogstashHandler',
                  'formatter': 'logstash',
                  'transport': 'logstash_async.transport.TcpTransport',
                  'host': 'myelkserver.com',
                  'port': 1026,
                  'database_path': './logstash.db',  # same results if None
              },
    },
    'loggers': {
        'logstash': {
                  'handlers': ['logstash'],
                  'level': 'DEBUG',
                  'propagate': True, 
              },
    }
}
```

```
>>>import logging
>>>logger = logging.getLogger("logstash")
>>>logger.debug('hello')  # no message is sent to remote
```

The following works which makes no sense to me, any ideas?

```
from logstash_async.handler import AsynchronousLogstashHandler
from logstash_async.transport import TcpTransport
from logstash_async.formatter import DjangoLogstashFormatter

lgr = logging.getLogger()
formatter = DjangoLogstashFormatter(message_type='django')
handler = AsynchronousLogstashHandler('myelkserver.com', 1026, database_path='./logstash.db', transport=TcpTransport)
handler.setFormatter(formatter)
lgr.addHandler(handler)
lgr.debug('test123') # this is received by remote
```

**Comment by eht16** [comment]
I don't see anything obvious as well :(.
You could check if the missing event from your Django app is at least in the `./logstash.db` (it's a simple SQLite database) and has just not been sent to the Logstash server yet.

The only difference between the Django config and the manual attempt seems to be the logger name. In the Django config you configured only the logger "logstash" to use the "logstash" handler. Maybe just try to add the "logstash" handler to the root logger and check if that makes any difference.
You could also try to set "disable_existing_loggers" to False in the Django logging config. However I think this shouldn't make any difference.

Otherwise, I'm also a bit out of ideas. In my Django projects it works well.
